name: hkt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - torchvision=0.11.0
  - cudatoolkit=11.3  # Remove this line if using CPU only
  - numpy=1.21.0
  - scipy=1.7.0
  - scikit-learn=1.0.0
  - tqdm
  - pip
  - pip:
    - transformers>=4.5.0,<5.0.0
    - sentencepiece>=0.1.95
